### ISSUE TITLE
Modify function block for function exit tracing

### ISSUE THREAD

**Issue by ariya** [ariya/esmorph#4]
Migrated from http://code.google.com/p/esprima/issues/detail?id=162.

Similar to function entrance tracing.

In this case we apply modification whenever the function is about to exit, both at the end of the function block and through the return statement.

Care must be taken so that the return statement inside another nested function (i.e. at different depth level) does not get marked as function exit.

**Comment by alfredwesterveld** [comment]
+1. Too bad this project is no longer maintained. What has been implemented is really cool!

**Comment by ariya** [comment]
This is now supported. w00t!

**Comment by alfredwesterveld** [comment]
cool :)
